Dev
guywilsonjr/ExtremeLifeServer pull request #6
Opened 2021-12-03 01:51 UTC by denmcca

Made changes to check TinyDB instance for game session ID before assigning chat channel. Chat channel must exist before chat service keys are forwarded to requesting host.

2021-12-03 20:36 UTC, guywilsonjr requested changes

2021-12-03 20:36 UTC, guywilsonjr commented on datamanager.py
> +        gq = Query()
gq unused

2021-12-03 20:36 UTC, guywilsonjr commented on datamanager.py
> +        gq = Query()
gq unused

2021-12-03 20:36 UTC, guywilsonjr commented on components/dbaccess/db.py
> +    print(repr(config))
I don't really care. did you mean to keep it in there? We might want to know, but it also looks like the type of thing acidentally left in

2021-12-03 20:36 UTC, guywilsonjr commented on scripts/chatdb_services.py
> +    """Check channel table and remove expired channels."""
No need to remove it per se, but if you ever import this anywhere it'll fail. this looks like it's missing some code.

2021-12-03 21:21 UTC, denmcca commented on scripts/chatdb_services.py
> +    """Check channel table and remove expired channels."""
It's a placeholder in case i wanted to create background services for the db. It won't crash since it has a doc string.

2021-12-04 21:54 UTC, guywilsonjr approved these changes

2021-12-04 21:56 UTC, merged